//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetingoLightUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255@255")]
        public string SCREEN_INDEX_0 {
            get {
                return ((string)(this["SCREEN_INDEX_0"]));
            }
            set {
                this["SCREEN_INDEX_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255@255")]
        public string SCREEN_INDEX_2 {
            get {
                return ((string)(this["SCREEN_INDEX_2"]));
            }
            set {
                this["SCREEN_INDEX_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public byte SCREEN_BRIGHTNESS {
            get {
                return ((byte)(this["SCREEN_BRIGHTNESS"]));
            }
            set {
                this["SCREEN_BRIGHTNESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool STARTUP_WITH_WINDOWS {
            get {
                return ((bool)(this["STARTUP_WITH_WINDOWS"]));
            }
            set {
                this["STARTUP_WITH_WINDOWS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte LED_COUNT_VER_RED {
            get {
                return ((byte)(this["LED_COUNT_VER_RED"]));
            }
            set {
                this["LED_COUNT_VER_RED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte LED_COUNT_VER_YELLOW {
            get {
                return ((byte)(this["LED_COUNT_VER_YELLOW"]));
            }
            set {
                this["LED_COUNT_VER_YELLOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte LED_COUNT_VER_BLUE {
            get {
                return ((byte)(this["LED_COUNT_VER_BLUE"]));
            }
            set {
                this["LED_COUNT_VER_BLUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public byte LED_COUNT_HOR_RED {
            get {
                return ((byte)(this["LED_COUNT_HOR_RED"]));
            }
            set {
                this["LED_COUNT_HOR_RED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public byte LED_COUNT_HOR_YELLOW {
            get {
                return ((byte)(this["LED_COUNT_HOR_YELLOW"]));
            }
            set {
                this["LED_COUNT_HOR_YELLOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public byte LED_COUNT_HOR_BLUE {
            get {
                return ((byte)(this["LED_COUNT_HOR_BLUE"]));
            }
            set {
                this["LED_COUNT_HOR_BLUE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255@255")]
        public string SCREEN_INDEX_1 {
            get {
                return ((string)(this["SCREEN_INDEX_1"]));
            }
            set {
                this["SCREEN_INDEX_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public short LED_TARGET_TIME_OFF {
            get {
                return ((short)(this["LED_TARGET_TIME_OFF"]));
            }
            set {
                this["LED_TARGET_TIME_OFF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public short LED_TARGET_TIME_ON {
            get {
                return ((short)(this["LED_TARGET_TIME_ON"]));
            }
            set {
                this["LED_TARGET_TIME_ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public byte MODE {
            get {
                return ((byte)(this["MODE"]));
            }
            set {
                this["MODE"] = value;
            }
        }
    }
}
